LanikSJ/ubo-filters

README.md
add-element.sh

Badge was one the next line moving it up and fixing suggestions by codacy.
N/A
Because I like pretty things. 🙂
Locally.

Move Badge and Fix Codacy Errors

---

.github/stale.yml

Add Stale Bot for PRs
N/A
Improve PRs
https://probot.github.io/apps/stale/

Add Stale Bot

---

README.md

Add GPLv3 Badge
N/A
More badges ... mmm good. 😁
https://github.com/Naereen/badges#gplv3-license

Add GPLv3 Badge

---

.travis.yml
README.md
checksum-sort.sh

Add Travis to every build and remove git commands from shell script.
N/A
1. Better code quality and automated testing.
2. Remove Git commands from shell script.
Used travis branch to test builds.

Add Travis Integration

---

README.md

Badges look weird on https://lanik.github.io/ubo-filters
Visit https://lanik.github.io/ubo-filters badges wrap onto a new line.
We like pretty things. 😁
Atom Markdown preview FTW!

Moving Badges to New Line

---

docs/index.md

Title is duplicated and needs a page title instead.
Title listed twice in GitHub Pages.
Fix GitHub Pages.
Travis CI and GitHub Pages.

Modify index.md

---

_config.yml

Remove duplicate _config.yml since it's not needed.
Possible breakage if the wrong config file gets read.
We like clean code. 😁
Travis and GitHub Pages.

Remove duplicate _config.yml

---

.travis.yml
README.md

Add Code Coverage Tests to Travis CI.
N/A
We ❤️ Code Coverage.
Travis CI

Add Code Coverage to Travis CI

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/lock.yml

Fix Markdown and Fix Lock Bot.
This PR fixes: https://github.com/LanikSJ/ubo-filters/issues/14
Lock Bot Threw and Error.
Travis CI

Markdown Fixes and Fix Lock Bot

---

README.md
docs/index.md

Update README and GitHub Pages Markdown Files
The README didn't match the GitHub Pages content
We ❤️ Markdown Pages
Travis CI
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

Update README and GitHub Pages

---

admiral-domains.txt
immortal-domains.txt
ubo-filters.txt

Add Terms and Conditions to Each Filter List
The need to indemnify the owner of the list
Thou shall not sue our asses
Travis CI
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

Add Terms and Conditions

---

README.md
docs/index.md
scripts/README.md

Cleanup README Markdown File
Use the correct line breaks in Markdown Files
Shouldn't use `<br>` when it's not needed
Travis CI
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

Cleanup README.md

---

filters/hilltopads-domains.txt

line endings ==> https://i.imgur.com/8Zjp0k9.png

Update Description + fix line endings

---

filters/adback-domains.txt

The date was different format on AdBack Domains List
Let's keep the same data format everywhere
Uniformity across all lists
Travis CI
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

Fix Date on AdBack Domains

---

README.md
docs/index.md

Change the language in README.md to be more concise. 
Some README.md language isn't clear.
We need concise documentation.
Travis CI
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

Update README.md Language

---

.dockerignore

Adding Docker Ignore
Git History and Stuff is getting into Docker container
Git History etc shouldn't be in the Docker container
Travis CI
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

Adding Docker Ignore

---

filters/combined-filters.txt

Update Combined Filters List with Changes from GetAdmiral List
Combined List Needs an Update Now That GetAdmiral List Has Been Updated
Keep All Filter Lists Up To Date
Travis CI & uBo
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

Update Combined Filters List

---

filters/admiral-domains.txt

[#commitcomment-34042517](https://git.io/fjwa4)

fix download address for uBo

---

filters/cryptomining-domains.txt

Block Duinocoin miners like https://github.com/sys-256/Duino-JS.

Add magi.duinocoin.com

---

.github/workflows/admiral-domains.yml
.github/workflows/combined-filters.yml
.github/workflows/fanboy-social.yml

Update GitHub Actions

---

scripts/addChecksum.pl
scripts/admiral-domains.sh
scripts/combined-filters.sh
scripts/malware-domains.sh

- Update `addChecksum.pl` upstream
- Update GitHub Actions according to above

Update Per Scripts and Actions Scripts

---

scripts/admiral-domains.sh
scripts/combined-filters.sh
scripts/malware-domains.sh

Update Perl Script Dependency

---

.github/workflows/combined-filters.yml
.github/workflows/fanboy-social.yml
.github/workflows/malware-domains.yml
scripts/admiral-domains.sh
scripts/combined-filters.sh
scripts/malware-domains.sh

- Update GitHub Actions with Perl Dependencies Installation

Update GitHub Actions with Perl Dependency Install

---

.github/workflows/admiral-domains.yml
.github/workflows/combined-filters.yml
.github/workflows/fanboy-social.yml
.github/workflows/malware-domains.yml
cpanfile

- Remove `cpanfile`
- Update GitHub Actions to Install `cpan` Dependency instead

Remove Cpanfile and Update GitHub Actions

---

.github/workflows/admiral-domains.yml
.github/workflows/combined-filters.yml
.github/workflows/fanboy-social.yml
.github/workflows/malware-domains.yml

- Remove Dev Dependency Installation for Perl

Update GitHub Actions To Remove Perl Deps

---

.github/workflows/admiral-domains.yml
.github/workflows/auto-approve-pr.yml
.github/workflows/combined-filters.yml
.github/workflows/fanboy-social.yml
.github/workflows/lock-threads.yml
.github/workflows/malware-domains.yml

- Update Names of GitHub Actions

Update GitHub Actions Names

---

filters/ubo-filters.txt

- Remove Atlassian Community Promo Banner
- Remove Costco Ad Banners

Add Atlassian Community and Costco

---

.github/workflows/combined-filters.yml
scripts/checksum-sort.sh
scripts/combined-filters.sh

- Disable Combined Filters GitHub Action
- Enabled All the Lines in Combined Filters Script
- Shell Script Fixes

Disable Combined Filters Update GitHub Action

---

filters/youtube-antiadblock.txt

- Update YouTube list from the article

Update YouTube Anti-Adblock List

---

filters/adback-domains.txt
filters/adkeeper-domains.txt
filters/admaven-domains.txt
filters/admeasures-domains.txt
filters/bt-contentza-domains.txt
filters/cdn-filter-list.txt
filters/cryptomining-domains.txt
filters/freecounterstat-domains.txt
filters/hilltopads-domains.txt
filters/istripper-domains.txt
filters/kitty-domains.txt
filters/macupload-domains.txt
filters/malware-domains.txt
filters/popads-domains.txt
filters/propellerads-domains.txt
filters/toradvertising-domains.txt
filters/unknown-domains.txt
filters/videoadex-domains.txt
filters/volumedata-domains.txt

- Update Modify Dates for All Filters Using New Script

Update Modify Dates for All Lists

---

filters/getadmiral-domains.txt

Imports from ghostery/broken-page-reports.
refs https://github.com/ghostery/broken-page-reports/issues/669
refs https://github.com/ghostery/broken-page-reports/issues/743

Update Admiral Domains

---

filters/getadmiral-domains.txt

- Update Checksum and Modified Date after #513

Update GetAdmiral Domains Checksum and Modified Date

---

.github/workflows/admiral-domains.yml

- Remove Admiral Domains Cron since it hasn't been updated since 2020 https://github.com/jkrejcha/AdmiraList/issues/39

Update Admiral Domains Cron

---

.github/workflows/lock-threads.yml
.github/workflows/stale-issues.yml

- Update Lock Threads GitHub Action
- Add Stale Issues GitHub Actions
- Modeled from Homebrew Org

Update Lock Threads and Add Stale Issues

---

.github/workflows/admiral-domains.yml
scripts/admiral-domains.sh

- Update Script to Pull From My Fork
- Enable GitHub Action

Enable Admiral Domains GitHub Action

---

_typos.toml

- Add Typos Ignore File
- Ignore Filters since they have misspelled class names etc.

Add Typos Ignore File

---

README.md

- Add `I Don't Care About Cookies` List

Add Cookie List to Supplemental Lists in README.md

---

filters/ubo-filters.txt

- Remove Hacker News bad filter
- Remove SoundCloud (Not in Use)
- Adjust NewEgg Image Block
- Adjust KRON4 QR Code Block
- Remove Startpage (Not in Use)

Remove Redundant & Bad Filters

---

filters/ubo-filters.txt

Add ESPN Empty Reactions Div

---

filters/ubo-filters.txt

Add Peacock TV AdBlocker Warning

---

filters/getadmiral-domains.txt

- Update checksum
- Update modified date

Update Checksum and Modified Date

---

filters/ubo-filters.txt

Add Shop Deals Div

---

filters/ubo-filters.txt

- LinkedIn Whitelist https://github.com/RedDragonWebDesign/block-everything/issues/20
- Add AWS Login Banner

Add LinkedIn WhiteList and AWS Sign In

---

filters/getadmiral-domains.txt

Reverts LanikSJ/ubo-filters#535
Fixes LanikSJ/ubo-filters#539

Revert Bad GitHub Actions Update to Admiral Domains Filter List

---

.github/ISSUE_TEMPLATE/bug.yml

- Update Bug Issue Template
- Correct a Bunch of Fields

Update Bug Issue Template

---

_config.yml

- Add AdBlock and AdBlock Plus

Update GitHub Pages Description

---

filters/ubo-filters.txt

- Allow YouTube Filter in Channel Page to Un-Break YouTube

Allow YouTube Filter in Channel Page

---

filters/ubo-filters.txt

- Add JFrog Banner
- Add GitLab Header Whitelist

Add JFrog Banner & GitLab Allow Header

---

.github/workflows/codeql.yml

- Use CodeQL Advanced
- Only on `scripts/*` Path

Switch to CodeQL Advanced

---

filters/ubo-filters.txt

- Remove Ad for Phone Book Report

Add USPhoneBook Banner Divs

---

.github/workflows/dead-domains-check.yml

- Add `dead-domains-check.yml`

Add Dead Domains Check

---

.github/workflows/dead-domains-check.yml

- Add Version to GitHub Action

Update Dead Domains Check

---

.github/dependabot.yml

* Add NPM Package Manager Updates

Update Dependabot Checks

---

.github/workflows/lock-threads.yml

- Updated Frequency of GitHub Action

Update Lock Threads

---

filters/malware-domains.txt

Update Malware Domains Filters List

---

.github/workflows/dead-domains-check.yml

- Add Checksum and Date Update

Update Dead Domains Check GitHub Action

---

.github/workflows/dead-domains-check.yml

- Update Warning Message
- Update Constant Name
- Update More Titles

Update Dead Domains GitHub Action

---

filters/ubo-filters.txt

- Removed Amazon Frequently Bought Div
```
https://www.amazon.com/Google-Pixel-Unlocked-Smartphone-Advanced/dp/B0CGTD5KVT/
```

Remove Amazon Frequently Bought Div

---

filters/ubo-filters.txt

Add SRE DevOps TOC List Block

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feat.yml

- Pull in Issue Template updates from webannoyances

Update Issue Templates

---

pnpm-lock.yaml

Update NodeJS Dependencies

---

scripts/FOP.py

Update FOP.py Ignore List

---

.github/workflows/node-update-deps.yml

- NodeJS Auto Update GitHub Action

Add NodeJS Auto Update GitHub Action

---

filters/ubo-filters.txt

- Add `vultr.com` and `hub.docker.com`

Add Filters to Personal Filter List

---

filters/ubo-filters.txt

- Menus Were Broken on Frong Page and Video Pages

Add YouTube White List to Unbreak Menus

---

filters/getadmiral-domains.txt

Adds regexmail.com to Admiral domains

Add domain to getadmiral-domains.txt

---

filters/ubo-filters.txt

Update Checksum and Date

---

.github/workflows/restyled.yml
filters/getadmiral-domains.txt
scripts/remove-lines.sh

- Update Filters, Actions & Scripts

Update Filters and Scripts

---

filters/ubo-filters.txt

Update uBO Filter List

---

README.md

- Remove Immortal Domains Link from README.md

Remove Immortal Domains Link

---

filters/ubo-filters.txt

Filter Updates from Local

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
filters/README.md
scripts/README.md
scripts/checksum-sort.sh

- Update Checksum Script
- Lint all README.md Files

Update Scripts and README Files

---

.github/workflows/admiral-domains.yml
.github/workflows/combined-filters.yml
.github/workflows/dead-domains-check.yml
.github/workflows/fanboy-social.yml
.github/workflows/node-update-deps.yml

- Resolve Issues with GitHub Actions Permissions

Fix GitHub Actions Permissions

---

scripts/FOP.py

- Update to the Filter Organizer and Pruner Script

Update FOP Script

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.markdownlint.json
LICENSE
README.md

- Fix Markdown Issues in All Files

Fix Markdown Issues
